### ISSUE TITLE
There is already a "ron" crate

### ISSUE THREAD

**Issue by flanfly** [lambdafu/ron-rs#2]
The name `ron` is already used for the [Rusty Object Notation](https://crates.io/crates/ron) crate. `swarm` is also [gone](https://crates.io/crates/swarm). I suggest we rename the crate to `ron-crdt` or something similar.

**Comment by lambdafu** [comment]
Sure, I think it's best to transfer this to you and then you can make the decision and rename the repo!

**Comment by flanfly** [comment]
I'm honored :bowing_man:

**Comment by flanfly** [comment]
I called it `ron-crdt` and published it on crates.io
